### ISSUE TITLE
BUG with the PUT method on the cart items api while trying to update the metadata list prop

### ISSUE THREAD

**Issue by danielmariz** [swellstores/swell-js#159] opened 2024-02-15 23:03 UTC
Hi team, I'm getting a weird issue while trying to update a product variant metadata but this occurs only on the second product variant added to the cart.
My scenario requires to send a custom metadata for a single variant so I'm using the PUT method to update when a client add a new option for the same variant

When adding the first product variant to the cart everything works fine:

1. cart is empty as you can see in the api response
![image](https://github.com/swellstores/swell-js/assets/1138727/ba0edcdc-ef05-4e1e-8afa-9493e0fce318)
2. now I added the first item via post method
![image (1)](https://github.com/swellstores/swell-js/assets/1138727/16bf6647-4a52-44a7-bd64-ec351b5bb870)
3. the payload is sent correctly
![image (2)](https://github.com/swellstores/swell-js/assets/1138727/41385bf0-176e-4353-9b8b-c00ddf6d1829)
4. and the response is also as expected, so it added an item with the metadata
![image (3)](https://github.com/swellstores/swell-js/assets/1138727/fc2ecc9e-db58-4273-9492-b28c78425fed)
5. now I'm adding a new item to the same variant on a PUT method for the item id
![image (4)](https://github.com/swellstores/swell-js/assets/1138727/130f68a9-a48a-4ea2-965c-ec5cce3f603d)
6. the payload is sent as documented using the $set object to override the whole metadata list
![image (5)](https://github.com/swellstores/swell-js/assets/1138727/3f898cdc-0c0b-4c46-bad9-0cd0ec0d1894)
7. the response is also correct the metadata it's being updated as expected
![image (6)](https://github.com/swellstores/swell-js/assets/1138727/2a372be4-f165-4e4e-a1d7-367caabc52cc)
8. now I'm gonna add a new product, the new product is also added using the POST method on the cart api
![image (7)](https://github.com/swellstores/swell-js/assets/1138727/ec027b82-17ea-4c1f-af59-69a42158a749)
9. the payload on the post method does not use the $set attribute
![image (8)](https://github.com/swellstores/swell-js/assets/1138727/03c5e91f-e1b1-4979-8d52-aba34e1d7dc0)
10. the response is correct with a new item id on the cart and correct metadata
![image (9)](https://github.com/swellstores/swell-js/assets/1138727/b69b63ac-1ab5-4dc3-adbd-05f531be68e2)
11. now I'm adding a new metadata item for the same variant using the item id, it uses the PUT method
<img width="867" alt="image" src="https://github.com/swellstores/swell-js/assets/1138727/92764f33-a946-4f83-b7e0-cf81552899e3">

12. the payload is sent using the $set  prop again
<img width="867" alt="image" src="https://github.com/swellstores/swell-js/assets/1138727/2ab8e7e8-bd7f-4ee1-88f0-c6ef3d1479dc">

13. but the response does not change the metadata but changes the quantity
<img width="876" alt="image" src="https://github.com/swellstores/swell-js/assets/1138727/8f000f03-b31f-4201-bb5f-10521c8304fa">

So in resume, the same calls with different behaviour from the api, I believe that using metadata like that is not a common pattern for you so you never caught this scenario before but is a requirement from my client because they don't want to treat sizes as a variant because will be more than 30 sizes combined with other 4 variant types and will be hard to manage the product content and prices. The issue only happens after the second product variant is added to the cart although I'm managing the first item with the same calls

**Comment by logeshswell** [comment] 2024-02-26 09:29
From my understanding, the issue is PUT method on the cart items API is not updating metadata values correctly for the second cart item.

> the payload is sent using the $set prop again

Can you share the correct screenshot of the request payload sent in Step-10?

**Comment by danielmariz** [comment] 2024-02-26 16:49
> From my understanding, the issue is PUT method on the cart items API is not updating metadata values correctly for the second cart item.
> 
> > the payload is sent using the $set prop again
> 
> Can you share the correct screenshot of the request payload sent in Step-10?

I believe you are asking about the step-11 which was duplicated from step-10 now I updated the screenshots from step-11 simulating updating the metadata for a second variant added in the cart. So the first variant works fine with the same approach and from the second variant the issue start to happen

**Comment by logeshswell** [comment] 2024-02-26 17:48
Can you try passing the request payload as follows for the PUT method?
```json
{
  "$set": {
    "metadata": {
      "sizes": []
    }
  }
}
```
It is not highly recommended to pass `$set` field in the middle of the payload.

**Comment by danielmariz** [comment] 2024-02-26 17:52
> Can you try passing the request payload as follows for the PUT method?
> 
> ```json
> {
>   "$set": {
>     "metadata": {
>       "sizes": []
>     }
>   }
> }
> ```
> 
> It is not highly recommended to pass `$set` field in the middle of the payload.

I've tried this approach but the docs seems to be outdate according to [this comment](https://github.com/orgs/swellstores/discussions/488#discussioncomment-8307834)

**Comment by logeshswell** [comment] 2024-02-27 16:15
Sorry, I was wrong with the request payload structure as I didn't notice that it's a frontend API.
Can you try passing the request payload as follows?
```json
{
  "metadata": {
    "$set": {
      "sizes": []
    }
  }
}
```
 
 I will also ensure my team to update the documentation:
 https://developers.swell.is/frontend-api/carts#update-cart-metadata

**Comment by danielmariz** [comment] 2024-02-27 16:36
> Sorry, I was wrong with the request payload structure as I didn't notice that it's a frontend API. Can you try passing the request payload as follows?
> 
> ```json
> {
>   "metadata": {
>     "$set": {
>       "sizes": []
>     }
>   }
> }
> ```
> 
> I will also ensure my team to update the documentation: https://developers.swell.is/frontend-api/carts#update-cart-metadata

the way you're suggesting also has issues

1. the first call for the variant is a POST on cart items api with the payload you suggested
<img width="392" alt="image" src="https://github.com/swellstores/swell-js/assets/1138727/dd28175b-e139-4b92-9d3b-462a23ac85bf">

2. the response for that returns the payload as expected
<img width="393" alt="image" src="https://github.com/swellstores/swell-js/assets/1138727/b95860ba-fbd8-4db4-b5b2-bd6a89e822e0">

3. the second call for the same variant is a PUT on the cart item id api with the  payload updating the sizes
<img width="394" alt="image" src="https://github.com/swellstores/swell-js/assets/1138727/4244b67b-53f9-4adb-82a0-8bafe89a8816">

4. the response for it changes the metadata shape so not consistent and hard to predict
<img width="390" alt="image" src="https://github.com/swellstores/swell-js/assets/1138727/dfc907bb-9ebd-4df9-a469-f5ae70e015e8">

so if you check the metadata object in the first call it returns sizes as a metadata property, but the second (update) puts the sizes inside an inner object with a key 0

When I tried to wrap the whole metadata object in the $set format than I could get it updated when adding items to the sizes array but not when removing an item, in that case the quantity changes but the sizes returns the removed index anyways. So still the api inconsistent  

:/

**Comment by danielmariz** [comment] 2024-02-28 00:19
The swell team needs to investigate this scenario when updating an item metadata containing a list by adding and removing items from this list from multiple variants in the cart items

**Comment by logeshswell** [comment] 2024-02-28 07:28
I am investigating this issue and will help you with the examples of adding and removing items from the `metadata` list field.

**Comment by logeshswell** [comment] 2024-02-28 10:20
I can also reproduce this issue in my store and I can confirm that it is a bug.
We'll take a deeper look at this issue and get back to you if I get some updates.

**Comment by logeshswell** [comment] 2024-02-28 10:23
@danielmariz Just for your information, the way you updated `metadata.sizes` field in the PUT request is correct as per your ticket description.

You can ignore the alternate suggestions provided by me about the usage of `$set`.

**Comment by danielmariz** [comment] 2024-03-20 16:23
Hi @logeshswell is there any plans for this fix in the short term? We're expecting on shipping to production soon so we might need to refactor on our side in order to make it work for us. Cheers!

**Comment by logeshswell** [comment] 2024-03-21 08:09
This issue has already been prioritized and is yet to be worked on. I don't have an ETA, but I will keep you posted if I get any updates.

**Comment by fourwordsnz** [comment] 2024-07-08 08:42
Hey are there any updates on this?

**Comment by logeshswell** [comment] 2024-07-09 11:50
@fourwordsnz No new updates as of now. I will inform my team to prioritize the fix quickly.

**Comment by fourwordsnz** [comment] 2024-09-02 08:42
any eta on this?

**Comment by logeshswell** [comment] 2024-10-19 14:38
The fix has been made and it should work fine now. Please check and confirm.

**Closed by logeshswell** 2024-10-19 14:38 UTC
Labels: bug
